# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/INTRA/chakal/workspace/project/ip_repo/zedboard_audio/constraints/zed_audio.xdc

# Block Designs: bd/project/project.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project || ORIG_REF_NAME==project}]

# IP: bd/project/ip/project_processing_system7_0_0/project_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_processing_system7_0_0 || ORIG_REF_NAME==project_processing_system7_0_0}]

# IP: bd/project/ip/project_processing_system7_0_axi_periph_0/project_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==project_processing_system7_0_axi_periph_0}]

# IP: bd/project/ip/project_rst_processing_system7_0_100M_0/project_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==project_rst_processing_system7_0_100M_0}]

# IP: bd/project/ip/project_zed_audio_0_0/project_zed_audio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_zed_audio_0_0 || ORIG_REF_NAME==project_zed_audio_0_0}]

# IP: bd/project/ip/project_xlconstant_0_0/project_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_xlconstant_0_0 || ORIG_REF_NAME==project_xlconstant_0_0}]

# IP: bd/project/ip/project_MY_AXI_AUDIO_0_0/project_MY_AXI_AUDIO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_MY_AXI_AUDIO_0_0 || ORIG_REF_NAME==project_MY_AXI_AUDIO_0_0}]

# IP: bd/project/ip/project_Volume_Pregain_0_0/project_Volume_Pregain_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_Volume_Pregain_0_0 || ORIG_REF_NAME==project_Volume_Pregain_0_0}]

# IP: bd/project/ip/project_FILTER_IIR_0_0/project_FILTER_IIR_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_FILTER_IIR_0_0 || ORIG_REF_NAME==project_FILTER_IIR_0_0}]

# IP: bd/project/ip/project_FILTER_IIR_0_1/project_FILTER_IIR_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_FILTER_IIR_0_1 || ORIG_REF_NAME==project_FILTER_IIR_0_1}]

# IP: bd/project/ip/project_Volume_Pregain_0_1/project_Volume_Pregain_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_Volume_Pregain_0_1 || ORIG_REF_NAME==project_Volume_Pregain_0_1}]

# IP: bd/project/ip/project_xbar_0/project_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_xbar_0 || ORIG_REF_NAME==project_xbar_0}]

# IP: bd/project/ip/project_xlconcat_0_0/project_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_xlconcat_0_0 || ORIG_REF_NAME==project_xlconcat_0_0}]

# IP: bd/project/ip/project_mixer_0_0/project_mixer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_mixer_0_0 || ORIG_REF_NAME==project_mixer_0_0}]

# IP: bd/project/ip/project_xlconcat_1_0/project_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_xlconcat_1_0 || ORIG_REF_NAME==project_xlconcat_1_0}]

# IP: bd/project/ip/project_xlconcat_2_0/project_xlconcat_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_xlconcat_2_0 || ORIG_REF_NAME==project_xlconcat_2_0}]

# IP: bd/project/ip/project_ZedboardOLED_0_0_2/project_ZedboardOLED_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_ZedboardOLED_0_0 || ORIG_REF_NAME==project_ZedboardOLED_0_0}]

# IP: bd/project/ip/project_ZedboardOLED_0_0_2/src/charLib/charLib.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==charLib || ORIG_REF_NAME==charLib}]

# IP: bd/project/ip/project_axi_gpio_0_0_1/project_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_axi_gpio_0_0 || ORIG_REF_NAME==project_axi_gpio_0_0}]

# IP: bd/project/ip/project_axi_gpio_1_0/project_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_axi_gpio_1_0 || ORIG_REF_NAME==project_axi_gpio_1_0}]

# IP: bd/project/ip/project_auto_pc_0_1/project_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_auto_pc_0 || ORIG_REF_NAME==project_auto_pc_0}]

# XDC: bd/project/ip/project_processing_system7_0_0/project_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==project_processing_system7_0_0 || ORIG_REF_NAME==project_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/project/ip/project_rst_processing_system7_0_100M_0/project_rst_processing_system7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==project_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==project_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/project/ip/project_rst_processing_system7_0_100M_0/project_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==project_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==project_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/project/ip/project_rst_processing_system7_0_100M_0/project_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/project/ip/project_xbar_0/project_xbar_0_ooc.xdc

# XDC: bd/project/ip/project_ZedboardOLED_0_0_2/src/charLib/charLib_ooc.xdc

# XDC: bd/project/ip/project_axi_gpio_0_0_1/project_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==project_axi_gpio_0_0 || ORIG_REF_NAME==project_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/project/ip/project_axi_gpio_0_0_1/project_axi_gpio_0_0_ooc.xdc

# XDC: bd/project/ip/project_axi_gpio_0_0_1/project_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==project_axi_gpio_0_0 || ORIG_REF_NAME==project_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/project/ip/project_axi_gpio_1_0/project_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==project_axi_gpio_1_0 || ORIG_REF_NAME==project_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/project/ip/project_axi_gpio_1_0/project_axi_gpio_1_0_ooc.xdc

# XDC: bd/project/ip/project_axi_gpio_1_0/project_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==project_axi_gpio_1_0 || ORIG_REF_NAME==project_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/project/ip/project_auto_pc_0_1/project_auto_pc_0_ooc.xdc

# XDC: bd/project/project_ooc.xdc
