# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/INTRA/chakal/workspace/project/vivado/project.cache/wt [current_project]
set_property parent.project_path /home/INTRA/chakal/workspace/project/vivado/project.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  /home/INTRA/chakal/workspace/project/ip_repo/SoC_Design/HDL/Audio_Mixer
  /home/INTRA/chakal/workspace/project/ip_repo/SoC_Design/IPs/OLED/ZedBoard_OLED_1.0
  /home/INTRA/chakal/workspace/project/ip_repo/zedboard_audio
  /home/INTRA/chakal/workspace/project/ip_repo/ip_repo_vivado/FILTER_IIR_1.0
  /home/INTRA/chakal/workspace/project/ip_repo/ip_repo_vivado/Volume_Pregain_1.0
  /home/INTRA/chakal/workspace/project/ip_repo/MY_AXI_AUDIO_1.0
} [current_project]
add_files /home/INTRA/chakal/workspace/project/vivado/project.srcs/sources_1/bd/project/ip/project_ZedboardOLED_0_0_2/src/charLib/charLib.coe
add_files /home/INTRA/chakal/workspace/project/vivado/project.srcs/sources_1/bd/project/project.bd
set_property used_in_implementation false [get_files -all /home/INTRA/chakal/workspace/project/vivado/project.srcs/sources_1/bd/project/ip/project_processing_system7_0_0/project_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/chakal/workspace/project/vivado/project.srcs/sources_1/bd/project/ip/project_rst_processing_system7_0_100M_0/project_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/chakal/workspace/project/vivado/project.srcs/sources_1/bd/project/ip/project_rst_processing_system7_0_100M_0/project_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/chakal/workspace/project/vivado/project.srcs/sources_1/bd/project/ip/project_rst_processing_system7_0_100M_0/project_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/chakal/workspace/project/vivado/project.srcs/sources_1/bd/project/ip/project_xbar_0/project_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/chakal/workspace/project/vivado/project.srcs/sources_1/bd/project/ip/project_ZedboardOLED_0_0_2/src/charLib/charLib_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/chakal/workspace/project/vivado/project.srcs/sources_1/bd/project/ip/project_axi_gpio_0_0_1/project_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/chakal/workspace/project/vivado/project.srcs/sources_1/bd/project/ip/project_axi_gpio_0_0_1/project_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/chakal/workspace/project/vivado/project.srcs/sources_1/bd/project/ip/project_axi_gpio_0_0_1/project_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/chakal/workspace/project/vivado/project.srcs/sources_1/bd/project/ip/project_axi_gpio_1_0/project_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/chakal/workspace/project/vivado/project.srcs/sources_1/bd/project/ip/project_axi_gpio_1_0/project_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/chakal/workspace/project/vivado/project.srcs/sources_1/bd/project/ip/project_axi_gpio_1_0/project_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/chakal/workspace/project/vivado/project.srcs/sources_1/bd/project/ip/project_auto_pc_0_1/project_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/chakal/workspace/project/vivado/project.srcs/sources_1/bd/project/project_ooc.xdc]
set_property is_locked true [get_files /home/INTRA/chakal/workspace/project/vivado/project.srcs/sources_1/bd/project/project.bd]

read_vhdl -library xil_defaultlib /home/INTRA/chakal/workspace/project/vivado/project.srcs/sources_1/bd/project/hdl/project_wrapper.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/INTRA/chakal/workspace/project/ip_repo/zedboard_audio/constraints/zed_audio.xdc
set_property used_in_implementation false [get_files /home/INTRA/chakal/workspace/project/ip_repo/zedboard_audio/constraints/zed_audio.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top project_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef project_wrapper.dcp

catch { report_utilization -file project_wrapper_utilization_synth.rpt -pb project_wrapper_utilization_synth.pb }
